### ISSUE TITLE
pbd_sim generates a sampled species tree that does not expand in time

### ISSUE THREAD

**Issue by richelbilderbeek** [rsetienne/PBD#5]
For the same seed, the trees generated for crown age `x` should be similar to a tree of crown age `x+e` (where `e` is a small value)

So these two are similar:

![plot1159](https://cloud.githubusercontent.com/assets/2098230/12089936/341a91e6-b2ea-11e5-9b4d-e3f94a35a7f1.png)
![plot1160](https://cloud.githubusercontent.com/assets/2098230/12089935/34190b5a-b2ea-11e5-8df7-fc54814cac65.png)

Then there is a major transition:

![plot1161](https://cloud.githubusercontent.com/assets/2098230/12089937/341ab8ba-b2ea-11e5-8617-dde0bf8ba95a.png)

This denotes that for the same seed one can have qualitatively different results dependent on stem age.

Here is the code, so you can check for yourself:

```
library(PBD)

rng_seed <- 42
species_initiation_rate_good_species <- 0.5
species_initiation_rate_incipient_species <- 0.5
speciation_completion_rate <- 1.0
extinction_rate_good_species <- 0.1
extinction_rate_incipient_species <- 0.1

for (age in seq(6,7,0.01))
{
  set.seed(rng_seed)
  pbd_output <- pbd_sim(c(species_initiation_rate_good_species,speciation_completion_rate,species_initiation_rate_incipient_species,extinction_rate_good_species,extinction_rate_incipient_species),age=age,soc=2,plot=FALSE)
  plot(pbd_output$tree)
}
```

**Comment by rsetienne** [comment]
Hoi Richel,

Goede check!
Maar ik denk dat het loos alarm is, omdat er een (completion) event 
gebeurt bij deze transitie. Je zou dit kunnen bestuderen door naar L0 te 
kijken in je output (pbd_output$L0).

Groet, Rampal

**Comment by rsetienne** [comment]
This is because there is a completion event at this transition. So no issue.
